### ISSUE TITLE
Please tag releases on GitHub

### ISSUE THREAD

**Issue by jonafato** [JasonLG1979/gnome-shell-extension-weather-in-the-clock#12]
Thanks for building this! I'd like to package the extension for NixOS and nixpkgs, which generally requires a tagged release to point to for builds. Can you tag the releases that get published to EGO?

**Comment by JasonLG1979** [comment]
No. Distro packages are pointless since a user can just install via EGO. EGO is the only install and distribution method supported by me. I don't tag releases because I only support the most recent version available from EGO and git master (which are usually the same thing) If you choose to package and distribute snapshots of master support will be on you.

**Comment by JasonLG1979** [comment]
You are of course free to fork the repo and add your own tags and point your build system to that. But again you assume all support and maintenance responsibilities.
