### ISSUE TITLE
First item displayed is always empty

### ISSUE THREAD

**Issue by tsujigiri** [JasonLG1979/gnome-shell-extension-weather-in-the-clock#6]
## Distro Name & Version
Arch Linux
## GNOME Shell Version
3.34.4
## Other Installed Extensions
* Emoji Selector
* Removable Drive Menu
## Expected Behavior
First item displayed shows valid time and temperature.
## Current Behavior

First item displayed always shows "01:00" as time and "--" as temperature. See [screenshot](https://drive.google.com/file/d/1EbWw5GZQ26BSUbUyPKsCpXVc78T1TFSO/view?usp=sharing).

 Also, is it supposed to show the weather in the top bar, too? Because it doesn't for me.

**Comment by JasonLG1979** [comment]
That screenshot is of the default built weather section of the notification menu. This extension has nothing to do with that. All it does is put the current weather condition icon and temp in the panel next to the clock if it's available. If it's not available for whatever reason you'll get what you got in the menu (again which I have nothing to do with) and my extension will show nothing in the panel.

Your issue is something to do with GNOME Weather not this extension.

**Comment by JasonLG1979** [comment]
See https://github.com/JasonLG1979/gnome-shell-extension-weather-in-the-clock/issues/5 for more insight.
